name: Parser Build and Test

on:  push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install bison
      run: |
       sudo apt-get update
       sudo apt-get install bison

    - name: run all
      run: |
        cd parser/
        make all
      
